### ISSUE TITLE
terraform plan not working 

### ISSUE THREAD

**Issue by jatinder10884** [traveloka/terraform-aws-elasticache-memcached#13] opened 2020-10-21 18:15 UTC
Hi ALL,

When I run the terraform-aws-elasticache-memcached module I got the below error

+++++++++++++++++++
Error: Variables not allowed

  on <value for var.security_group_ids> line 1:
  (source code not available)

Variables may not be used here.

Error: No value for required variable

  on variables.tf line 42:
  42: variable "security_group_ids" {

The root module input variable "security_group_ids" is not set, and has no
default value. Use a -var or -var-file command line argument to provide a
value for this variable.

**Comment by jatinder10** [comment] 2020-10-22 05:11
Is there anyone who can help on this ?

**Comment by nin9swells** [comment] 2021-09-27 10:24
Hello,
Sorry that no one replying here. I'm closing this ticket since it might not be relevant anymore.
But if you still have encounter this issue, please provide version Terraform, AWS provider, and module version. And a chunk of your configuration and step to reproduce, would be really helpful to troubleshoot this issue.

**Closed by nin9swells** 2021-09-27 10:24 UTC
Labels: bug
